### PR TITLE
sets dialTLS to true when using tls config options

### LINKED ISSUE #242: Add dial option to specify that TLS should be used.
In Dial,
```go
if do.dialTLS {
```
But t`dialTLS` isn't set in
```go
func DialTLSConfig(c *tls.Config) DialOption {
	return DialOption{func(do *dialOptions) {
		do.tlsConfig = c
	}}
}
```
Consequently, only way to get TLS enable is DialURL with `rediss`:
```go
	if u.Scheme == "rediss" {
		options = append([]DialOption{{dialTLS}}, options...)
	}
```

### PR DESCRIPTION
**Pull request by chrisvdg**
closes #242

### CODE REVIEW

**Comment by zhangruiskyline** [comment]
Hi, is this feature(dialTLS function) in 1.1.0? I did check and can not find it

**Comment by garyburd** [comment]
This feature is included in 1.2.0 (which I created moments ago).

**Comment by zhangruiskyline** [comment]
great news, so glide install should pick up this change right now?:)

**Comment by garyburd** [comment]
I don't know. Although I have heard of glide, I have not used it or read the documentation.

**Comment by zhangruiskyline** [comment]
actually it did. thx, glide and yams are golfing package management tool.

**Pull request closed without merging**
