### PR TITLE
Add support for Redis Cluster

### PR DESCRIPTION
**Pull request by zalecn**
Support simple cluster client.
Will be Support, in the future:
1. Multiple keys command in different slot, like MGet foo1 foo2.
2. Cluster command.

fix: [https://github.com/garyburd/redigo/issues/12](url)

### CODE REVIEW

**Comment by garyburd** [comment]
As stated in the [README](https://github.com/garyburd/redigo#contributing), I am looking for a new maintainer for the project. PRs for major features will not be accepted until a new maintainer is found.

**Comment by sioncojp** [comment]
Hi.
Will this PR be added function that be able to select multiple nodes?

**Comment by sioncojp** [comment]
Hi, any idea when this will be merged?

**Comment by garyburd** [comment]
This feature can be added in another package.  I am not adding significant new features to Redigo.

**Pull request closed without merging**
