### PR TITLE
Add Int64s helper function

### LINKED ISSUE #192: add a Int64s() function
AFAIK there is no function Int64s for redis reply, I thinks it is necessary for a int64 array.

### PR DESCRIPTION
**Pull request by crackerplace**
Implemented a helper function for int64s reply.

@garyburd

Fixes #192

### CODE REVIEW

**Comment by garyburd** [comment]
Call Int64 in a loop to avoid use of reflection in ScanSlice.

**Comment by crackerplace** [comment]
@garyburd Sure.If needed I can modify Ints function as well to avoid using ScanSlice.

**Comment by garyburd** [comment]
Yes, that will be helpful

**Comment by crackerplace** [comment]
Sorry,some delay in this.Will be done by weekend.

**Comment by crackerplace** [comment]
@garyburd How should we handle nil in the reply interface slice.Should we ignore and continue and in which case the specific entry in the result slice will be the zero value.ScanSlice has similar logic.

**Comment by garyburd** [comment]
Yes, use the zero value.  

If an application should call Values directly if it needs to distinguish between nil and zero in the result.

**Pull request closed without merging**
